### ISSUE TITLE
Need to clear acquisition array during scan

### ISSUE THREAD

**Issue by nswdxqq** [dynarithmic/twain_library_source#21]
I'm evaluating the library for a scan project, and facing one problem with image acquisition as follows:
1. I need to acquire many images from scanner with one scan process;
2. I'm using buffered transfer from scanner;
3. During scanning a file for each image is created and the DIB is not needed anymore once the file is saved;
4. The memory keeps increasing during scanning and the program is out of memory finally;
So I'm curious if there is any way to clear the array of acquisition during scanning? And I'm using C# by the way.

**Comment by dynarithmic** [comment]
Please see the [suggested solution](https://github.com/dynarithmic/twain_library/issues/45)

**Comment by dynarithmic** [comment]
[Closed](https://github.com/dynarithmic/twain_library/issues/45)
