### ISSUE TITLE
TWAIN_SetCapValues/TWAIN_SetCapValuesEx doesn't work with TW_FRAME data type.

### ISSUE THREAD

**Issue by jichen20210919** [dynarithmic/twain_library_source#26]
Hi,team, we are using a 32 bit dtwain32u.dll to set custom frames, but we find it always returns fail.
by tracing the code, we find in function,
static bool performSetCap(DTWAIN_HANDLE DLLHandle, DTWAIN_SOURCE Source, TW_UINT16 lCap, DTWAIN_ARRAY pArray,
                          LONG lContainerType, LONG lSetType, LONG nDTWAIN_ArrayType, CTL_ArrayType eType,
                          LONG TwainTypeValue)

following code is used to extract frames from array.
```
                ConvertFrom lVal;
                pHandle->m_ArrayFactory->get_value(pArray, 0, &lVal);
                lValue = ConverterFn::convert(lVal, nullptr);
                bOk = SetOneCapValue(DLLHandle, Source, static_cast<TW_UINT16>(lCap), static_cast<CTL_EnumSetType>(lSetType), lValue, static_cast<TW_UINT16>(TwainTypeValue)) ? true : false;
```
and we find it always returns invalid frame value, that is why TWAIN_SetCapValuesEx  always fail.
following code snippet work well
```
            if ((TwainTypeValue != TWTY_FRAME)) {
                ConvertFrom lVal;
                pHandle->m_ArrayFactory->get_value(pArray, 0, &lVal);
                lValue = ConverterFn::convert(lVal, nullptr);
                bOk = SetOneCapValue(DLLHandle, Source, static_cast<TW_UINT16>(lCap), static_cast<CTL_EnumSetType>(lSetType), lValue, static_cast<TW_UINT16>(TwainTypeValue)) ? true : false;
            }
            else {
                DTWAIN_FRAME frame;
                DTWAIN_FLOAT left, top, right, bottom;
                DTWAIN_ArrayGetAt(pArray, 0, &frame);
                DTWAIN_FrameGetAll(frame, &left, &top, &right, &bottom);
                TwainFrameInternal lVal(left, top, right, bottom);
                TW_FRAME twFrame = lVal.To_TWFRAME();
                bOk = SetOneCapValue(DLLHandle, Source, static_cast<TW_UINT16>(lCap), static_cast<CTL_EnumSetType>(lSetType), twFrame, static_cast<TW_UINT16>(TwainTypeValue)) ? true : false;
            }
```

**Comment by dynarithmic** [comment]
In the AllDemos.sln, there is a demo project called `GetSetCapabilities`.  In there is an attempt to set the frame type.  You should compile the sorce, compile the demos, and test GetSetCapabilities (it takes a while to compile the source code and demos).

I tested this with the demo TWAIN source from the TWAIN Working Group, and the frame is set correctly without any coding changes.  Maybe you encountered something else, but the code that does this looks slightly different than the code you are showing.

Starting from [this line](https://github.com/dynarithmic/twain_library_source/blob/6124e440515773089ec873e75c382c5b37e9648f/source/cpp/ctlsetgetcaps.cpp#L248) is where the setting of the type is done.  Note that this is for TW_ONEVALUE containers.

I will still investigate, but I did not encounter the failure before.

**Comment by dynarithmic** [comment]
Just as a test, what if you used `DTWAIN_SetCapValuesEx2` using the following arguments:

`DTWAIN_SetCapValuesEx2(Source, ICAP_FRAMES, DTWAIN_CAPSET, DTWAIN_CONTONEVALUE, TWTY_FRAME, Array);`

This is how the C++ wrapper library makes the call to set the frame, as demonstrated by the GetSetCapabilities demo project.  Possibly the DTWAIN_SetCapValuesEx is not getting the correct container or frame type, but please check the lower level `DTWAIN_SetCapValuesEx2` API call with the above parameters.

**Comment by dynarithmic** [comment]
I wrote a small application using the following snippet of code:

```
            DTWAIN_ARRAY arrayFrame = DTWAIN_ArrayCreateFromCap(Source, ICAP_FRAMES, 1);
            DTWAIN_ArrayFrameSetAt(arrayFrame, 0, 0, 0, 4.5, 8);
            DTWAIN_SetCapValuesEx(Source, ICAP_FRAMES, DTWAIN_CAPSET, DTWAIN_CONTONEVALUE, arrayFrame);
```

The source used is the TWAIN sample source from the TWAIN Working Group.  The frame is (0, 0, 4.5, 8).  I was able to set the frame successfully using the calls above.

Possibly you are not creating the frame this way.  If so, then this may throw off how DTWAIN will process the capability that handles frames.

**Comment by jichen20210919** [comment]
Hi, Thanks for your update, looks the issue is not reproduced, please let me know the git hash, and compile environment in your test

**Comment by dynarithmic** [comment]
ok, so it may be a JNI or Java issue and the language binding .  The issue doesn't seem to be the DTWAIN library itself.  

Please note that the Java interface will be changing to one that to me is a better abstraction.   The Java / JNI code you are using will be deprecated very soon.  

In the new Java version, there is a demo that shows setting and getting frames that seems to work correctly.   I have given you access to [the new Java repo](https://github.com/dynarithmic/twain_library-java).  Please clone or get this version and see if the frame is set correctly.

Right now, the code is still under development and the documentation is basically non-existing.  But the demo programs should get you an idea of how to use the new code.  The JNI layer also has changed a bit, so make sure you read the README in the home page of that repositiory.

**Comment by dynarithmic** [comment]
Also the boost vesion used is 1.81.

**Comment by jichen20210919** [comment]
I see, thank you. very helpful to me.

**Comment by dynarithmic** [comment]
Released the new Java version [here](https://github.com/dynarithmic/twain_library-java).  

The GetSetCapabilities demo program shows the TW_FRAME being set and retrieved.
